Upgrade docusaurus to 3.0.0-rc.1
bitwarden/contributing-docs pull request #226
Opened 2023-10-30 11:04 UTC by Hinton

## Objective

2023-10-30 11:05 UTC, Hinton commented on package.json
> +  },
I've opened an upstream PR to docusaurus-lunr-search to avoid these.

2023-10-31 18:21 UTC, Hinton commented
Noteworthy change:

```:::warning``` admonitions are now rendered differently. View https://ps-docusaurus-3.contributing-docs.pages.dev/getting-started/server/database/ef/ and compare it to https://contributing.bitwarden.com/getting-started/server/database/ef/

2023-10-31 19:41 UTC, withinfocus commented
Do you want this considered for merge already, or is this to test beforehand? I'd think we can make some copytext improvements so you don't need to do the kind of escaping seen here.

2023-10-31 21:14 UTC, Hinton commented
@withinfocus I think it's "working" as expected. We should figure out if we want to do anything about the warning visual changes. I'm also open for modifying the text to avoid escaping, but the escaping itself is pretty harmless.

2023-11-01 14:22 UTC, withinfocus approved these changes
I improved the copytext to avoid some escaping. Looks good to me! Do we wait for the Lunr improvement though?

2023-11-06 13:50 UTC, MGibson1 requested changes
It looks like you were rewriting to avoid un-named links, but misseed two

2023-11-06 13:50 UTC, MGibson1 commented on docs/getting-started/server/sso/local.md
> +9.  You can test your user configuration by navigating to \<http://localhost:8090/simplesaml>, then
⚠️ only first angle bracket escaped. escape both or neither

2023-11-06 13:50 UTC, MGibson1 commented on docs/getting-started/server/sso/local.md
> +\<http://localhost:8090/simplesaml/module.php/core/authenticate.php?as=example-userpass> and click
⚠️ only first angle bracket escaped. escape both or neither

2023-11-06 14:02 UTC, withinfocus approved these changes

2023-11-06 14:03 UTC, merged