Extended title for ADR 0013
bitwarden/contributing-docs pull request #30
Opened 2022-12-14 21:31 UTC by trmartin4

## Objective

2022-12-14 22:18 UTC, MGibson1 reviewed
Seems reasonable to me, @Hinton what do you think? IIRC this title is off because you wanted a bigger scope but we limited ourselves

2022-12-15 16:33 UTC, trmartin4 commented
Perhaps to maintain consistency and clearly delineate the scope, we could title it "Service request/response folder structure" to parallel "Angular folder structure"

2022-12-15 17:45 UTC, Hinton commented
Perhaps we could rename it to `Deprecate global request/response models`?

2022-12-15 18:33 UTC, trmartin4 commented
@Hinton that sounds great!  I've updated it.

2022-12-15 19:30 UTC, Hinton reviewed
We should change the filename while we're at it

2022-12-15 20:08 UTC, trmartin4 commented
> We should change the filename while we're at it

Done.  I adjusted the title in the document as well.

2022-12-15 20:26 UTC, Hinton approved these changes

2022-12-15 20:29 UTC, Hinton requested changes

2022-12-15 20:29 UTC, Hinton commented on docs/architecture/adr/0013-deprecate-global-request-response-models.md
> +title: 0013 - Deprecate global request/response models
We can remove the title since it's identical to the header below.

2022-12-15 20:29 UTC, Hinton commented on docs/architecture/adr/0013-deprecate-global-request-response-models.md
> +title: 0013 - Deprecate global request/response models
```suggestion
```

2022-12-15 21:06 UTC, Hinton approved these changes

2022-12-15 21:19 UTC, merged