Start documenting the SDK architecture
bitwarden/contributing-docs pull request #342
Opened 2024-04-17 07:11 UTC by Hinton

## Objective

2024-04-18 16:12 UTC, coltonhurst requested changes
This is great, thanks @Hinton 

Two small items

2024-04-18 16:12 UTC, coltonhurst commented on docs/architecture/sdk/data-models.md
> +interface. Care must be taken to avoid exposing the inner workings on the SDK including it's data
```suggestion
interface. Care must be taken to avoid exposing the inner workings on the SDK including its data
```

2024-04-18 16:12 UTC, coltonhurst commented on docs/architecture/sdk/data-models.md
> +The SDK also maintains internal models
```suggestion
The SDK also maintains internal models:
```

For consistency with the `Public interface` section

2024-04-19 13:10 UTC, coltonhurst submitted a review, later dismissed

2024-04-29 17:33 UTC, withinfocus reviewed
Few small things.

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/index.md
> +[Confluence](https://bitwarden.atlassian.net/wiki/spaces/DEV/pages/517898288/Rust+Learning+Resources).</Bitwarden>
❓ Do we link to internal systems on this site? Not sure I have noticed that before. I guess if it's behind the Bitwarden veil we are good though.

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/index.md
> +- Promotes clear ownership of features.
⛏️ With just two bullets I usually like to just make this one sentence, in the above paragraph.

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/index.md
> +Many language bindings utilize the `bitwarden-c` crate which exposes a C API. This is then combined
```suggestion
Many language bindings utilize the `bitwarden-c` crate that exposes a C API. This is then combined
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/index.md
> +platforms, more specifically we publish android and iOS libraries with Kotlin and Swift bindings.
```suggestion
platforms, more specifically we publish Android and iOS libraries with Kotlin and Swift bindings, respectively.
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/index.md
> +[`sdk-swift` repository](https://github.com/bitwarden/sdk-swift).
```suggestion
[GitHub Packages](https://github.com/bitwarden/sdk/packages/1945788) in the SDK repository.
The Swift package is published in the
[`sdk-swift` repository](https://github.com/bitwarden/sdk-swift).
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/data-models.md
> +- **Response models**: Returns data from the SDK, one example is `ProjectResponse`.
```suggestion
- **Response models**: Returns data from the SDK e.g. `ProjectResponse`.
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/data-models.md
> +- **Api models**: These are [auto-generated models](./server-bindings.md) that are used to interact
```suggestion
- **API models**: These are [auto-generated models](./server-bindings.md) that are used to interact
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/data-models.md
> +- **View models**: These are models that generally represents a decrypted state, examples are
⛏️ There are a few "These are"s that could be omitted as that's implied.

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/server-bindings.md
> +- `bitwarden-api-api`: For the `Api` service, which contains most of the server side functionality.
```suggestion
- `bitwarden-api-api`: For the `Api` service that contains most of the server side functionality.
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/server-bindings.md
> +- `bitwarden-api-identity`: For the `Identity` service, which is used for authentication.
```suggestion
- `bitwarden-api-identity`: For the `Identity` service that is used for authentication.
```

2024-04-29 17:33 UTC, withinfocus commented on docs/architecture/sdk/server-bindings.md
> +It's highly recommended to not expose the request and response models of the generated bindings and
❓ Do we want to suggest something different if we intend to manage memory as much as possible? Should we mention memory security at all?

2024-04-30 17:25 UTC, withinfocus approved these changes

2024-05-02 09:44 UTC, merged