Add special note for EDD and EF
bitwarden/contributing-docs pull request #398
Opened 2024-07-29 14:12 UTC by rkac-bw

## 🎟️ Tracking

## 📔 Objective

Add specific info in regards to implementing EDD process for Entity framework Only Databases with Code Migrations (Self host for example)

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-29 14:36 UTC, Hinton commented
Is this needed? To my knowledge we don't use EF migrations for cloud and unified has no requirement for EDD.

2024-07-29 17:44 UTC, withinfocus commented
> Is this needed? To my knowledge we don't use EF migrations for cloud and unified has no requirement for EDD.

EF migrations are used for SM in the cloud right? I'd rather be consistent in our approach nonetheless though. It would be ideal to see a PR that includes EDD-prescribed changes both in a traditional DbUp migration script as well as an EF one.

2024-07-29 17:45 UTC, withinfocus requested changes
Your lint is failing -- make sure that's running locally for you per [the setup guide](https://github.com/bitwarden/contributing-docs?tab=readme-ov-file#install).

2024-07-29 17:45 UTC, withinfocus commented on docs/contributing/database-migrations/edd.mdx
> +## EF-Only Databases with Code Migrations
```suggestion
## EF-only databases with code migrations
```

2024-07-29 20:41 UTC, Hinton commented
No, SM uses regular migrations since using the EF framework for half our migration and hand written for the rest would be very difficult to understand.

For the delete scenario we should be fine having EF migrations that immediately delete the value. We will lose the ability to roll back though but for a delete that should be fine as we never rollback self-hosted instances.

There are more complex scenarios like column rename that requires some juggling with EF. And requires 3 deployments + 1 data migration.

1. Add column `new`, update code to write both `old` and `new`. <- DB & code deploy.
2. Run DB migration copying all `old` to `new`. <- DB
3. Removing code references to `old`. <- Code
4. Remove `old` from database. <- DB

2024-08-08 04:36 UTC, eliykat commented
Is there a consensus here? I need to drop some columns currently - which approach should I be using?

Regarding the PR itself - it would be useful to have a timeline showing both database frameworks side-by-side. e.g.

---

Example: dropping a column

| C# Entity | MSSQL | EF |
| -- |-- | -- |
| No change | Give the parameter a default value in all stored procedures | No change |
| Release |
| Delete the property (migration) | No change | Configure the column as a shadow property (no migration) |
| Release |
| No change | Drop the column | Delete the shadow property (migration) |

---

Maybe there is a better way to represent this.

2024-08-08 04:37 UTC, eliykat requested changes

2024-08-08 04:37 UTC, eliykat commented on docs/contributing/database-migrations/edd.mdx
> +
How do I do this? I had a look at https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties but it wasn't obvious how that maps to our implementation.

2024-11-13 17:42 UTC, withinfocus commented
As discussed we're got gonna EDD EF at this time.

2024-11-13 17:42 UTC, closed without merging