[PM-11873] Add Database Testing Instructions
bitwarden/contributing-docs pull request #480
Opened 2024-11-20 21:00 UTC by justindbaur

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11873

## 📔 Objective

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-20 22:00 UTC, withinfocus commented
Any guess as to why we didn't get a deployment?

2024-11-20 22:07 UTC, justindbaur commented
> Any guess as to why we didn't get a deployment?

@withinfocus Maybe because the last commit is a month old?

2024-11-20 22:20 UTC, withinfocus requested changes

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +Since Bitwarden has multiple database options (4), testing them all automatically is incredibly
🎨 I'd leave "4" out of this, as it could potentially change and this would be an easy miss.

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +`Infrastructure.IntegrationTest` project comes in, it allows setting up tests similarly to how the
```suggestion
`Infrastructure.IntegrationTest` project comes in, allowing the setup of tests similarly to how the
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +databases are consumed in the application. Through their common interface, generally an
```suggestion
databases are consumed in the applications through their common interfaces, generally an
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +`I*Repository`. These tests are automatically ran on all supported databases in our testing
```suggestion
`I*Repository`. These tests are automatically executed on all supported databases in our testing
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +To create a new database test, just add the `[DatabaseTheory]` and `[DatabaseData]` attributes to
```suggestion
To create a new database test just add the `[DatabaseTheory]` and `[DatabaseData]` attributes to
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +`User.AccountRevisionDate` then the same EF implementation should do that as well. Then by running
```suggestion
`User.AccountRevisionDate` then the same EF implementation should do that as well. By running
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +the test against all variants, we are ensuring all the variants are feature equal. Locally, you may
```suggestion
the test against all variants we are ensuring all the variants are feature-equal. Locally, you may
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +want to only the SQL Server tests along with one EF implementation, SQLite is often the easiest.
```suggestion
want to only run the SQL Server tests along with one EF implementation; SQLite is often the easiest in that situation.
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +The databases are expected to have the latest migrations applied to them.
```suggestion
The databases are expected to have the latest migrations applied.
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +order they are applied, user secrets, environment variables prefixed with `BW_TEST_`, and command
```suggestion
order they are applied: user secrets, environment variables prefixed with `BW_TEST_`, and command
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +[.NET Configuration](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration). In the
```suggestion
[.NET Configuration](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration) in the
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +```C#
```suggestion
```csharp
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +`Sqlite`. The `UseEf` property is only utilized it the `Type` is set to `SqlServer`, by default
```suggestion
`Sqlite`. The `UseEf` property is only utilized if the `Type` is set to `SqlServer`; by default
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +`SqlServer` will be configured with the Dapper repositories but by setting `UseEf` to `true`, it
```suggestion
`SqlServer` will be configured with the Dapper repositories, however by setting `UseEf` to `true` it
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +disable one database but not delete the entry, it can be helpful if you are encountering a problem
```suggestion
disable one database but not delete the entry; it can be helpful if you are encountering a problem
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +You can also configure the tests just like the pipeline, read more below.
```suggestion
You can also configure the tests just like the pipeline.
```

2024-11-20 22:20 UTC, withinfocus commented on docs/contributing/testing/database/index.md
> +The pipeline uses environment variables, an example entry you might add is:
```suggestion
The pipeline uses environment variables. An example entry you might add is:
```

2024-11-21 04:15 UTC, eliykat reviewed
@addisonbeck also had some changes and improvements in https://github.com/bitwarden/contributing-docs/pull/457, can these PRs be combined at all?

You would also be interested in his [related changes](https://github.com/bitwarden/server/pull/4912) to `migrate.ps1` - I think this is fairly essential to devs being able to set up and tear down their local integration testing dbs.

I think those PRs are blocked on [my feedback](https://github.com/bitwarden/server/pull/4912#discussion_r1811719851) which suggested changing the structure of the keys in user secrets.

2024-11-21 21:01 UTC, addisonbeck commented
> I think those PRs are blocked on https://github.com/bitwarden/server/pull/4912#discussion_r1811719851 which suggested changing the structure of the keys in user secrets.

Yep! I haven't made it back around to these yet.

2025-01-16 19:07 UTC, addisonbeck commented
@justindbaur I've merged and adapted this page into the PR I had specifically for running the tests locally: https://github.com/bitwarden/contributing-docs/pull/457

2025-01-21 20:34 UTC, closed without merging