[PM-15201] Add info to clarify where to find email contents
bitwarden/contributing-docs pull request #481
Opened 2024-11-22 21:39 UTC by JimmyVo16

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-15201

## 📔 Objective

Adding some more information to make it more explicit on how to find the email content locally.
## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-11-25 03:59 UTC, eliykat requested changes
I found where this information currently is: https://contributing.bitwarden.com/getting-started/server/guide#mailcatcher . (I don't know why I couldn't find it last week!)

Can you please link to that section rather than repeating information. e.g. "See the [Setup Guide] for more information about Mailtrap."

2024-11-25 21:55 UTC, eliykat requested changes

2024-11-25 21:55 UTC, eliykat commented on docs/getting-started/server/advanced-setup.md
> +[Setup Guide](https://contributing.bitwarden.com/getting-started/server/guide/#mailcatcher) for more
Please use relative links when linking within the docs. e.g. `[Setup Guide](./guide.md#mailcatcher)`.

2024-11-27 02:21 UTC, eliykat approved these changes
Thank you!

2024-11-27 21:10 UTC, jrmccannon approved these changes

2024-11-27 22:24 UTC, merged